version: "3.8"
services:
  draftivist_api:
    build:
      context: ./cyoa
      dockerfile: Dockerfile.prod
    command: gunicorn cyoa.wsgi -b 0.0.0.0:8000
  draftivist_ui:
    build:
      context: ./draftivist-ui
      dockerfile: Dockerfile.prod
    command: nginx -g  "daemon off;"
    ports:
      - '80:80'
    restart: always
