version: "3.8"
services:
  staging:
    build:
      image: "nonsensesynapse/draftivist:${VERSION_TAG}"
#      context: .
#      dockerfile: Dockerfile.prod
#      # env variables are not available when building an image, so we read them
#      # from the .env file and pass them into the Dockerfile as ARGs
#      args:
#        API_HOST: "${API_HOST}"
#        STATIC_PATH: "${STATIC_PATH}"
    command: gunicorn cyoa.wsgi -b 0.0.0.0:8000 --workers 3
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - PROJECT_ENVIRONMENT="STAGING"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./startup:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file: .env
volumes:
  db_data: {}