version: "3.8"
services:
  draftivist_ui:
    build:
      context: ./draftivist-ui
      dockerfile: Dockerfile.prod
    command: nginx -g  "daemon off;"
    ports:
      - '80:80'
    restart: always