version: "3.8"
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile.jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
volumes:
  jenkins_data: {}