version: "3.8"
services:
  draftivist_api:
    build:
      context: ./draftivist_api
      dockerfile: Dockerfile.prod
    command: gunicorn cyoa.wsgi -b 0.0.0.0:8000 --workers 3
    restart: always
    ports:
      - "8000:8000"
    env_file: draftivist_api/.env
  draftivist_ui:
    build:
      context: ./draftivist_ui
      dockerfile: Dockerfile.prod
    command: nginx -g  "daemon off;"
    ports:
      - '80:80'
    restart: always
