version: "3.8"
services:
  draftivist_api:
    build: ./draftivist_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./draftivist_api:/code/draftivist_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
  draftivist_ui:
    build: ./draftivist_ui
    command: "/bin/sh -c 'while true; do sleep 15; done'"
    volumes:
      - ./draftivist_ui:/code/draftivist_ui
    ports:
      - "3000:3000"
    stdin_open: true  # Prevents the docker container from trying to open a browser window when the react app starts
    env_file: .env
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./startup:/docker-entrypoint-initdb.d
    ports:
          - "5433:5432"
    env_file: .env
volumes:
  db_data: {}
