version: "3.8"
services:
  draftivist_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn cyoa.wsgi -b 0.0.0.0:8000 --workers 3
    restart: always
    ports:
      - "8000:8000"
    env_file: draftivist_api/.env
