# build environment
FROM node:14
RUN mkdir /code
RUN mkdir /code/draftivist_ui
WORKDIR /code/draftivist_ui
COPY package.json /code/draftivist_ui/
RUN yarn install
COPY . /code/draftivist_ui/
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
