FROM python:3.9-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

RUN mkdir /code
RUN mkdir /code/draftivist_api
WORKDIR /code/draftivist_api

COPY requirements.txt /code/draftivist_api/
RUN pip install -r requirements.txt

COPY . /code/draftivist_api
