FROM python:3.9-buster
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
RUN mkdir /code/draftivist_api
WORKDIR /code/draftivist_api
COPY . /code/draftivist_api
RUN pip install -r requirements.txt
