# Generated by Django 3.1 on 2020-09-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.campaign')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_text', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaign')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='api.issue')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatementSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_statements', to='api.campaignresponse')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.issue')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.statement')),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('COVER_PHOTO_DESKTOP', 'COVER_PHOTO_DESKTOP'), ('COVER_PHOTO_MOBILE', 'COVER_PHOTO_MOBILE')], max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('min_width', models.IntegerField(default=None)),
                ('max_width', models.IntegerField(default=None)),
                ('min_height', models.IntegerField(default=None)),
                ('max_height', models.IntegerField(default=None)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media_type',
            },
        ),
        migrations.AlterModelTable(
            name='campaign',
            table='campaign',
        ),
        migrations.AlterModelTable(
            name='issue',
            table='issue',
        ),
        migrations.AlterModelTable(
            name='statement',
            table='statement',
        ),
        migrations.AlterModelTable(
            name='statementselection',
            table='statement_selection',
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='api.campaign')),
            ],
            options={
                'db_table': 'campaign_recipient',
            },
        ),
        migrations.CreateModel(
            name='CampaignMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.campaign')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mediatype')),
            ],
            options={
                'db_table': 'campaign_media',
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='api.campaign')),
            ],
            options={
                'db_table': 'draft',
            },
        ),
        migrations.RemoveField(
            model_name='statementselection',
            name='campaign_response',
        ),
        migrations.DeleteModel(
            name='CampaignResponse',
        ),
        migrations.AddField(
            model_name='statementselection',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_statements', to='api.draft'),
            preserve_default=False,
        ),
    ]
