# Generated by Django 3.0.8 on 2020-08-26 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_survey_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_text', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Campaign')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='api.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='StatementSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_statements', to='api.CampaignResponse')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Issue')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Statement')),
            ],
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='question_option',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='survey_response',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
