# Generated by Django 3.1 on 2020-08-30 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200826_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('COVER_PHOTO_DESKTOP', 'COVER_PHOTO_DESKTOP'), ('COVER_PHOTO_MOBILE', 'COVER_PHOTO_MOBILE')], max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('min_width', models.IntegerField(default=None)),
                ('max_width', models.IntegerField(default=None)),
                ('min_height', models.IntegerField(default=None)),
                ('max_height', models.IntegerField(default=None)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media_type',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='campaign',
            table='campaign',
        ),
        migrations.AlterModelTable(
            name='campaignresponse',
            table='campaign_response',
        ),
        migrations.AlterModelTable(
            name='issue',
            table='issue',
        ),
        migrations.AlterModelTable(
            name='statement',
            table='statement',
        ),
        migrations.AlterModelTable(
            name='statementselection',
            table='statement_selection',
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='api.campaign')),
            ],
            options={
                'db_table': 'campaign_recipient',
            },
        ),
        migrations.CreateModel(
            name='CampaignMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.campaign')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mediatype')),
            ],
            options={
                'db_table': 'campaign_media',
            },
        ),
    ]
