# Generated by Django 3.0.8 on 2021-01-06 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_custom_statements', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'campaign',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='api.Campaign')),
            ],
            options={
                'db_table': 'issue',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SessionMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('remote_addr', models.CharField(blank=True, max_length=40, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'session_meta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StatementSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NEEDS_REVIEW', 'Needs Review'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='NEEDS_REVIEW', max_length=20)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.Issue')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'statement_submission',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='api.Issue')),
                ('submission_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement', to='api.StatementSubmission')),
            ],
            options={
                'db_table': 'statement',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('created', models.DateTimeField(auto_now=True)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='recipients', to='api.Campaign')),
            ],
            options={
                'db_table': 'recipient',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='auth.Group')),
            ],
            options={
                'db_table': 'organization',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='STARTED', max_length=20)),
                ('session_key', models.CharField(max_length=40, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='api.Campaign')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='api.Issue')),
                ('statements', models.ManyToManyField(related_name='drafts', to='api.Statement')),
            ],
            options={
                'db_table': 'draft',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='api.Organization'),
        ),
    ]
