# Generated by Django 3.0.8 on 2021-01-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
