# Generated by Django 3.0.8 on 2021-02-08 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('api', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='group',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='organization',
        ),
        migrations.AddField(
            model_name='campaign',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
