# Generated by Django 3.0.8 on 2021-02-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210208_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_small',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('COVER', 'Cover'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20, null=True),
        ),
    ]
