# This is a basic workflow to help you get started with Actions

name: Staging Deploy Test

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    name: 'Deploy container to staging server'
    steps:
      -
        name: Clone Github Repo
        uses: actions/checkout@master
#       -
#         name: Configure Docker context
#         uses: arwynfr/actions-docker-context@v1
#         with:
#           docker_host: 'ssh://someone@example.domain.tld'
#           context_name: 'draftivist_staging'
#           ssh_cert: ${{ secrets.SSH_CERT }}
#           ssh_key: ${{ secrets.SSH_KEY }}
      -
        name: Deploy to staging
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ${{ secrets.STAGING_HOST }}
          ssh_private_key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.STAGING_SSH_PUBLIC_KEY }}
#           deployment_mode:: docker-compose
          stack_file_name: docker-compose.staging.yaml
          args: up -d
        env:
          POSTGRES_DB: draftivist
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
          PROJECT_ENVIRONMENT: STAGING
