# This is a basic workflow to help you get started with Actions

name: Staging Deploy Test

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    name: 'Deploy container to staging server'
    steps:
#       -
#         name: Clone Github Repo
#         uses: actions/checkout@master
      -
        name: Deploy Container on Staging
        uses: appleboy/ssh-action@v0.1.4
        env: 
          POSTGRES_DB: draftivist
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
          PROJECT_ENVIRONMENT: STAGING
        with:
          HOST: ${{ secrets.STAGING_HOST }}
          USERNAME: ${{ secrets.STAGING_USER }}
          KEY: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          envs: POSTGRES_DB,POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_HOST,POSTGRES_PORT,PROJECT_ENVIRONMENT
          script: |
            # Pull latest
            # docker image pull nonsensesynapse/draftivist:staging 

            # Run the new container
            # docker run -d --expose 8000:8000 nonsensesynapse/draftivist:staging gunicorn cyoa.wsgi -b 0.0.0.0:8000 --workers 3
