# This is a basic workflow to help you get started with Actions

name: Staging Deploy Test

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    name: 'Deploy container to staging server'
    steps:
#       -
#         name: Clone Github Repo
#         uses: actions/checkout@master
      -
        name: Deploy Container on Staging
        uses: appleboy/ssh-action@v0.1.4
        env: 
          POSTGRES_DB: draftivist
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
          PROJECT_ENVIRONMENT: STAGING
        with:
          HOST: ${{ secrets.STAGING_HOST }}
          USERNAME: ${{ secrets.STAGING_USER }}
          KEY: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          envs: POSTGRES_DB,POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_HOST,POSTGRES_PORT,PROJECT_ENVIRONMENT
          script: |
            echo "test 123 test 123 test 123"
            echo $POSTGRES_DB
            # Pull latest
            docker image pull nonsensesynapse/draftivist:staging 

            # Stop the old container
            docker stop draftivist_staging
            docker rm draftivist_staging

            # Run the new container
            docker run -d -p 8000:8000 --name draftivist_staging \
            --env POSTGRES_DB --env POSTGRES_USER --env POSTGRES_PASSWORD --env POSTGRES_HOST --env POSTGRES_PORT --env PROJECT_ENVIRONMENT \
            nonsensesynapse/draftivist:staging

            # Give the container access to the other staging containers
            docker network connect draftivist_default draftivist_staging
